import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const dataPath = path.join(__dirname, '..', 'data', 'cv.json')
const outPath = path.join(__dirname, '..', 'src', 'data', 'cv.ts')

const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'))

const types = `export type Experience = {
  company: string
  role: string
  start: string
  end: string
  description: string
}

export type Education = {
  institution: string
  degree: string
  start: string
  end: string
}

export type Project = {
  name: string
  description: string
  url: string
  tech: string
}

export type Stat = {
  value: string
  label: string
}

export type SkillCategory = {
  category: string
  items: string[]
}`

const cvString = JSON.stringify(data, null, 2)
const file = `// Auto-generated from data/cv.json. Do not edit this file by hand.\n\n${types}\n\nexport const cv = ${cvString} as const\n`

fs.writeFileSync(outPath, file)
console.log('Generated src/data/cv.ts from data/cv.json')
