import fs from 'fs'
import path from 'path'
import { fileURLToPath, pathToFileURL } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const dataPath = path.join(__dirname, '..', 'data', 'cv.json')
const outPath = path.join(__dirname, '..', 'src', 'data', 'cv.ts')

const types = `export type Experience = {
  company: string
  role: string
  start: string
  end: string
  description: string
}

export type Education = {
  institution: string
  degree: string
  start: string
  end: string
}

export type Project = {
  name: string
  description: string
  url: string
  tech: string
  cover: string
  logo: string
  featured: boolean
  images: string[]
}

export type Stat = {
  value: string
  label: string
}

export type SkillCategory = {
  category: string
  items: string[]
}

export type Certification = {
  name: string
  issuer: string
  purpose: string
  logo: string
  status: 'doing' | 'done' | 'not-started'
}`

function toPublicCv(data) {
  const clone = structuredClone(data)
  if (Array.isArray(clone.certifications)) {
    clone.certifications = clone.certifications.filter(
      (cert) => cert.status === 'done' || cert.status === 'doing'
    )
  }
  if (Array.isArray(clone.references)) {
    clone.references = clone.references.map((ref) => {
      const publicRef = { ...ref }
      delete publicRef.phone
      delete publicRef.email
      return publicRef
    })
  }
  return clone
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/"/g, '&quot;')
}

function updateIndexMeta(data) {
  const rootDir = path.join(__dirname, '..')
  const indexPath = path.join(rootDir, 'index.html')
  const photoSrc = path.join(rootDir, 'src', 'assets', 'photo.jpg')
  const photoDest = path.join(rootDir, 'public', 'images', 'profile.jpg')
  const siteUrl = String(data.website || 'https://steiniemils.com').replace(/\/$/, '')
  const name = String(data.name || 'CV')
  const role = String(data.title || 'Developer')
  const description = String(data.hook || data.summary || `Personal CV of ${name}`).slice(0, 200)
  const pageTitle = `${name} — ${role}`
  const canonical = `${siteUrl}/`
  const imageUrl = `${siteUrl}/images/profile.jpg`

  if (fs.existsSync(photoSrc)) {
    fs.mkdirSync(path.dirname(photoDest), { recursive: true })
    fs.copyFileSync(photoSrc, photoDest)
  }

  const meta = [
    `<title>${escapeHtml(pageTitle)}</title>`,
    `<meta name="description" content="${escapeHtml(description)}" />`,
    `<meta name="author" content="${escapeHtml(name)}" />`,
    `<link rel="canonical" href="${escapeHtml(canonical)}" />`,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="${escapeHtml(name)}" />`,
    `<meta property="og:title" content="${escapeHtml(pageTitle)}" />`,
    `<meta property="og:description" content="${escapeHtml(description)}" />`,
    `<meta property="og:url" content="${escapeHtml(canonical)}" />`,
    `<meta property="og:image" content="${escapeHtml(imageUrl)}" />`,
    `<meta property="og:locale" content="en_IS" />`,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${escapeHtml(pageTitle)}" />`,
    `<meta name="twitter:description" content="${escapeHtml(description)}" />`,
    `<meta name="twitter:image" content="${escapeHtml(imageUrl)}" />`,
  ].join('\n    ')

  let html = fs.readFileSync(indexPath, 'utf-8')
  if (!html.includes('<!-- cv-meta:start -->')) {
    throw new Error('index.html is missing cv-meta markers')
  }
  html = html.replace(
    /<!-- cv-meta:start -->[\s\S]*?<!-- cv-meta:end -->/,
    `<!-- cv-meta:start -->\n    ${meta}\n    <!-- cv-meta:end -->`,
  )
  fs.writeFileSync(indexPath, html)
}

export function generateCv() {
  const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'))
  const publicData = toPublicCv(data)
  const cvString = JSON.stringify(publicData, null, 2)
  const file = `// Auto-generated from data/cv.json. Do not edit this file by hand.\n\n${types}\n\nexport const cv = ${cvString} as const\n`
  fs.writeFileSync(outPath, file)
  updateIndexMeta(data)
  console.log('Generated src/data/cv.ts from data/cv.json')
  console.log('Updated index.html meta from data/cv.json')
}

const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (invokedDirectly) generateCv()
