import fs from 'fs'
import path from 'path'
import { fileURLToPath, pathToFileURL } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const dataPath = path.join(__dirname, '..', 'data', 'cv.json')
const outPath = path.join(__dirname, '..', 'src', 'data', 'cv.ts')

const types = `export type Experience = {
  company: string
  role: string
  start: string
  end: string
  description: string
}

export type Education = {
  institution: string
  degree: string
  start: string
  end: string
}

export type Project = {
  name: string
  description: string
  url: string
  tech: string
}

export type Stat = {
  value: string
  label: string
}

export type SkillCategory = {
  category: string
  items: string[]
}

export type Certification = {
  name: string
  issuer: string
  purpose: string
  status: 'doing' | 'done' | 'not-started'
}`

function toPublicCv(data) {
  const clone = structuredClone(data)
  if (Array.isArray(clone.certifications)) {
    clone.certifications = clone.certifications.filter(
      (cert) => cert.status === 'done' || cert.status === 'doing'
    )
  }
  if (Array.isArray(clone.references)) {
    clone.references = clone.references.map((ref) => {
      const publicRef = { ...ref }
      delete publicRef.phone
      delete publicRef.email
      return publicRef
    })
  }
  return clone
}

export function generateCv() {
  const data = JSON.parse(fs.readFileSync(dataPath, 'utf-8'))
  const publicData = toPublicCv(data)
  const cvString = JSON.stringify(publicData, null, 2)
  const file = `// Auto-generated from data/cv.json. Do not edit this file by hand.\n\n${types}\n\nexport const cv = ${cvString} as const\n`
  fs.writeFileSync(outPath, file)
  console.log('Generated src/data/cv.ts from data/cv.json')
}

const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href
if (invokedDirectly) generateCv()
